### ISSUE TITLE
Implement serialization of factorio 2.0 personal logistic slots

### ISSUE THREAD

**Issue by Cooldude2606** [clusterio/clusterio#689]
Introduced by #686 in [inventroy_sync/serialize.lua](https://github.com/clusterio/clusterio/blob/05ca4eb25edfc12ebca6479620bcb3cad1572dee/plugins/inventory_sync/module/serialize.lua#L80)

To get all first party plugins into a bare minimum working state for factorio 2.0 the serialization of personal logistics was not implemented. This should be implemented using the new api while maintaining backwards compatibilty with the `v2_logistic_api` flag.

**Comment by Danielv123** [comment]
The existence of logistics group poses some challenges.

1. assign the group of the same name on the destination server if it exists, otherwise create it with the same selections
2. Create a new section not assigned to the group, porting over all the requests
3. Use whichever group is the newest, bound to cause all kinds of issues with state management
4. Create server specific groups, ex Groupname [523495] and strip the ID when going back to the origin server
5. Just overwrite it with whatever you brought with you
6. Sync logistics groups between servers independently of inventories

I am leaning towards a combination of 1 + 6.

**Comment by Cooldude2606** [comment]
[As disccused](https://discord.com/channels/450361298220351489/450361298220351491/1310950886054297693), an initial implementation of syncing unnamed groups will be sufficient until we decide how we want to handle named groups. The options have been reduced to:
1) Create an empty group if the group does not exist on the server.
2) Populate the group with the correct requests, but only if it did not exist.
3) Any new requests are placed into a unnamed group.
4) A new logistics sync plugin is created.
